### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by marksev1** [kmi/node-red-contrib-noble#11]
I get this error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'node-red-contrib-noble' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose install initial load of /usr/lib/package.json
5 verbose readDependencies loading dependencies from /usr/lib/package.json
6 silly cache add args [ 'node-red-contrib-noble', null ]
7 verbose cache add spec node-red-contrib-noble
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'node-red-contrib-noble',
8 silly cache add   scope: null,
8 silly cache add   name: 'node-red-contrib-noble',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed node-red-contrib-noble@latest
10 verbose addNamed "latest" is being treated as a dist-tag for node-red-contrib-noble
11 info addNameTag [ 'node-red-contrib-noble', 'latest' ]
12 silly mapToRegistry name node-red-contrib-noble
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'node-red-contrib-noble',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'node-red-contrib-noble',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/node-red-contrib-noble
17 verbose addNameTag registry:https://registry.npmjs.org/node-red-contrib-noble not in flight; fetching
18 verbose request uri https://registry.npmjs.org/node-red-contrib-noble
19 verbose request no auth needed
20 info attempt registry request try #1 at 3:46:16 PM
21 verbose request id 577fcd90149bf7f7
22 http request GET https://registry.npmjs.org/node-red-contrib-noble
23 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
24 info attempt registry request try #2 at 3:46:26 PM
25 http request GET https://registry.npmjs.org/node-red-contrib-noble
26 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
27 info attempt registry request try #3 at 3:47:26 PM
28 http request GET https://registry.npmjs.org/node-red-contrib-noble
29 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
29 verbose stack     at Object.exports._errnoException (util.js:870:11)
29 verbose stack     at errnoException (dns.js:32:15)
29 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:78:26)
30 verbose cwd /home/msev
31 error Linux 3.16.0-70-generic
32 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-red-contrib-noble"
33 error node v4.4.3
34 error npm  v2.15.1
35 error code EAI_AGAIN
36 error errno EAI_AGAIN
37 error syscall getaddrinfo
38 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
39 error If you need help, you may report this error at:
39 error     https://github.com/npm/npm/issues
40 verbose exit [ 1, true ]

**Comment by marksev1** [comment]
Sorry my bad, had bad internet connection. Closing issue.
